[global]
flavor = "hugo"
disable = ["MD033"]

respect-gitignore = true

[MD004]
style = "dash"  # Unordered list style (asterisk, plus, dash, consistent)

[MD013]
line-length = 500  # Line length
code-blocks = false  # Exclude code blocks from line length check
tables = false  # Exclude tables from line length check
headings = true  # Include headings in line length check
